### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ryanhammonds** [ryanhammonds/burst_user_study#1]
- [ ] Finalize simulation parameters
- [ ] Analysis of burst detection algorithms (e.g. bycycle, dualthresh) to determine if algorithms can accurately identify bursts. May help us know if we need to adjust simulation parameters.
- [x] Randomize order of signals displayed (in index.js)
- [x] ~~Link responses to google sheet (see [here](https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server/tree/master))~~ Firebase database
- [ ] Deploy on voytekresearch

**Comment by kguarian** [comment]
"Undo" mechanic

**Comment by voytek** [comment]
Snap window tool to the current plot and axes. Right now it's possible to move the whole burst selection window tool entirely off the plot.

**Comment by voytek** [comment]
Is it possible to "nudge" the whole window left / right using the keyboard? It'd also be nice to expand / contract the left- and right-most edges using keys as well, for fine-tuning the window.
